# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- oldrel
- release
- devel

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ggplot2-dev
      - dplyr-dev
